### ISSUE TITLE
Minecraft 1.17 is out

### ISSUE THREAD

**Issue by EsserGaming** [comp500/BorderlessMining#17]
I would like to see this mod on 1.17 because this mod really helps out if you alt-tab alot and want to use fullscreen

**Comment by Felix14-v2** [comment]
You can easily run 1.16 version on Minecraft 1.17. All you need is to remove the version dependency in the fabric.mod.json file
![image](https://user-images.githubusercontent.com/75726196/131211851-555c8c9a-3bf5-48f8-8d2d-a7c745424750.png)

**Comment by EsserGaming** [comment]
Still, better safe than sorry 😄

**Comment by comp500** [comment]
Done! [Hope](https://github.com/comp500/BorderlessMining/issues/11) [y'all](https://github.com/comp500/BorderlessMining/issues/13) [are](https://github.com/comp500/BorderlessMining/issues/14) [happy](https://github.com/comp500/BorderlessMining/issues/16).
