### ISSUE TITLE
Fullscreen resolution not changing with borderless mining

### ISSUE THREAD

**Issue by endoverlord423** [comp500/BorderlessMining#22]
when i set my fullscreen resolution to 1920x1080 instead of 2560x1440, for some reason with borderless mining it stays at 1440p. i have tried changing it in the installation settings, with sodium extra, and with the fullscreen resolution slider. it only changes to 1080p when i don't have borderless mining installed or i disable it in the mod settings
![image](https://user-images.githubusercontent.com/93725152/147968534-2831437e-4648-4623-9c5c-4ac23f758a23.png)

**Comment by comp500** [comment]
Borderless fullscreen does not and cannot change your screen resolution; use the Windows resolution settings to control the resolution of your screen.

**Comment by endoverlord423** [comment]
i just want to change the in game resolution for minecraft, not the resolution for everything

**Comment by comp500** [comment]
Well there isn't anything I can do about that... it's just how borderless fullscreen works. You could try something like [Resolution Control](https://www.curseforge.com/minecraft/mc-mods/resolutioncontrol) if you're doing so for better performance.
