### ISSUE TITLE
Add the option to only enable when tabbed out

### ISSUE THREAD

**Issue by nrbxyz** [comp500/BorderlessMining#23]
Running borderless fullscreen all the time gives half the fps compared to regular fullscreen, and it is only useful when tabbed out, so I thought it would be cool if there was a config option that makes it so that it switches to borderless fullscreen only when tabbed out

**Comment by comp500** [comment]
Could you try my test build in https://github.com/comp500/BorderlessMining/issues/19, to see if it improves or resolves the FPS issues?

**Comment by comp500** [comment]
Closing: this isn't really something I want to pursue, as I would like to resolve FPS issues instead of working around them, and such an option if it were even possible would still break compatibility with overlays and screenshot tools.
