### ISSUE TITLE
Incompatibility with Skip Transitions

### ISSUE THREAD

**Issue by CodeF53** [comp500/BorderlessMining#27]
Mirror issue on their github: https://github.com/trufflezmc/skip-transitions/issues/2

Launching the game with both of the mods causes the following crash:
https://paste.ee/p/QTaS8

**Comment by comp500** [comment]
Are you sure the crash doesn't occur when Borderless Mining isn't present? Borderless Mining doesn't touch any of the classes that mod mixes into, it shouldn't be incompatible...

**Comment by CodeF53** [comment]
Disabling borderless mining makes the crash not occur

**Comment by comp500** [comment]
Ah, I think I might be classloading `MinecraftClient` wayyy too early... but I have no idea why that causes the mixin injection crash.
