### ISSUE TITLE
Sodium

### ISSUE THREAD

**Issue by ghost** [comp500/BorderlessMining#34]
I use Sodium for my fps improvements with alot of other mods tho i dont see the borderless option. So could you add Sodium support?

**Comment by ghost** [comment]
Never mind i fixed this by downloading the alpha version and enabling fullscreen (tho maybe the description could be changed in sodium? it still says normal fullscreen but it is windowed full screen)

**Comment by comp500** [comment]
The original version still has Sodium support, Sodium just replaces the video settings menu so you can't see the option. Press Shift+P in the video settings menu to see the option, or use Mod Menu to configure it in Borderless Mining's settings screen.
