### ISSUE TITLE
Multi-monitor fullscreen without surround/eyefinity

### ISSUE THREAD

**Issue by woutwoot** [comp500/BorderlessMining#35]
Title says it all really. I currently have a triple monitor setup, but the only way to conveniently play with those is by stretching a Minecraft window over all of them. I was wondering if this mod could help actually making it fullscreen over those 3 monitors. Would be awesome, but thank you for the mod either way!

**Comment by comp500** [comment]
I think you can do this already, by setting custom monitor coordinates in the settings (requires Mod Menu to edit). Probably requires a bit of experimentation to get the right coordinates :P

**Comment by woutwoot** [comment]
I'm certainly going to give that a go. Will report back if that helps in any way :) Thanks for the tip!

**Comment by woutwoot** [comment]
That totally worked! Indeed took some experimentation, but got it working perfectly now! Cherry on the cake would be to be able to keep the GUIs on the middle monitor instead of stretched as well, but this is awesome already. Thanks a lot for the mod and that suggestion!
