### ISSUE TITLE
1.19?

### ISSUE THREAD

**Issue by shigeon1999** [comp500/BorderlessMining#36]

**Comment by taciturnaxolotl** [comment]
Yes please, I can help and have time to learn how to update fabric mods.

**Comment by comp500** [comment]
I've nearly finished porting it myself, just need to fix the fullscreen resolution slider mixin.

**Comment by taciturnaxolotl** [comment]
Okay I started trying to do it but quickly got bogged down as I had never attempted it before.

**Comment by WaffleDevs** [comment]
> 



> I've nearly finished porting it myself, just need to fix the fullscreen resolution slider mixin.

This is an amazing thing to hear. I can't stand having my minecraft minimize when I click on my second monitor!

**Comment by Mythbusters123** [comment]
> I've nearly finished porting it myself, just need to fix the fullscreen resolution slider mixin.

Thank God lol

**Comment by tjalp** [comment]
> I've nearly finished porting it myself, just need to fix the fullscreen resolution slider mixin.

Can we expect an update soon or are you not done yet porting?
Thank you for putting in the effort! :)
