### ISSUE TITLE
Microstutters

### ISSUE THREAD

**Issue by PweSol** [comp500/BorderlessMining#40]
Constant microstuttering on borderless fullscreen when using V-Sync (in-game/NVIDIA Control Panel) and/or limiting the maximum FPS. Doesn't happen in exclusive fullscreen. This happens regardless the frame rate (tested on 360Hz monitor). No, https://github.com/comp500/BorderlessMining/issues/19 doesn't fix this.

Edit: I'm unable to reproduce this issue on 1.19 with Release 1.1.5+1.19. Actually, Release 1.1.5+1.19 seems to work perfectly without any other issues I experienced before, except for https://github.com/comp500/BorderlessMining/issues/2

**Comment by comp500** [comment]
Could you send your full system details, particularly monitor and GPU? Screenshots of the game with Alt+F3 in exclusive fullscreen, borderless fullscreen (particularly with #19) and a window would be helpful.

**Comment by comp500** [comment]
Closing: seems to be fixed?
