### ISSUE TITLE
Incompatibility with two other mods

### ISSUE THREAD

**Issue by muluffel** [comp500/BorderlessMining#44]
(1.19)
Optifabric seems to have incompatibilities when it is intalled together with [Slight GUI Modifications](https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications) and  [Optifabric ](https://www.curseforge.com/minecraft/mc-mods/optifabric/) (and [Optifine](https://optifine.net/home)). Only the combination of those 3 mods crashes the game. No other combinations. See the following:

Optifabric (and Optifine ) + Borderless Mining = working
Optifabric (and Optifine ) + Slight GUI Modifications = working
Borderless Mining + Slight GUI Modifications = working
Borderless Mining + Optifabric (and Optifine ) + Slight GUI Modifications = [crash](https://mclo.gs/lpG4GpK)

Shedaniel, the dev of Slight GUI Modification closed my issue to his mod with the comment "I don't care about optifine", so maybe there's a possible fix by Borderless Mining?

**Comment by comp500** [comment]
As mentioned in #43 and #42, please report these issues to Optifabric.

**Comment by muluffel** [comment]
Already did that. Thanks for the quick response, I hope it's Optifabric's fault
