### ISSUE TITLE
crash when clicking options with optifine installed

### ISSUE THREAD

**Issue by Jaaaaas** [comp500/BorderlessMining#46]
when I click options there is saving world screen and then crash
![Przechwytyw12anie](https://user-images.githubusercontent.com/109037311/178155580-6171dcf3-dbb1-4efb-bf89-27494f267a8c.PNG)
![Przechwytywa12nie](https://user-images.githubusercontent.com/109037311/178155582-3cf758f7-a24c-43ae-b40a-fbf1946a3ff4.PNG)

**Comment by comp500** [comment]
Duplicate of #42 #43 #45.
