### ISSUE TITLE
I think this mod can work without the Fabric API

### ISSUE THREAD

**Issue by Sanluli36li** [comp500/BorderlessMining#5]
I don’t see anything in the code that calls Fabric API Mod.
So I tried to edit the fabric.mod.json in the release version, remove the fabric dependency and put it in the mods directory without the Fabric API. It seems to be working perfectly
```
"depends": {
    "fabricloader": "\u003e\u003d0.7.2",
    "minecraft": "~1.16-alpha.20.12.a"
  },
```
So I think we can remove the fabric dependency. In this way, I don't need to install Fabric API in my client.

**Comment by comp500** [comment]
If I remember correctly, it uses fabric-resource-loader (a module in the API) to load translation strings in the config screen. I'll see if I can make it bundle just fabric-resource-loader so there's no dependency on the entirety of Fabric API.
