### ISSUE TITLE
1.19 version: Launching places the window halfway off the screen

### ISSUE THREAD

**Issue by cobaltCrowsprite** [comp500/BorderlessMining#51]
Launching the game puts my minecraft window halfway off of the screen diagonally and I can't seem to find a fix

**Comment by comp500** [comment]
Which exact Borderless Mining version are you using? What other mods are you using? Is this fixed by toggling fullscreen?

**Comment by Arknia08** [comment]
Hi, I've been having the same issue with the 1.18.2 version of the mod.

![screen](https://user-images.githubusercontent.com/89664276/189520035-834f27c3-e3ce-4a5e-9446-7f62f181bed1.png)

The game window is offset a bit onto my right monitor. The severity of this seems to be random, sometimes it's offset by a few dozen pixels and sometimes it's shifted by 1/3 of the screen.

I get this behavior in any scenario but for this screenshot I made a fresh fabric install, and BorderlessMining was the only mod installed.
The fabric version I used was 0.14.7-1.18.2,
the mod version was 1.1.2+1.18.2.
(The GPU I'm using is a GTX 1080Ti with driver 512.95. In case that is of any importance.)

Hope this helps.

**Comment by comp500** [comment]
The 1.18.2 version does not have the fix I implemented for this issue, and I don't generally backport to or support older versions.

**Comment by Arknia08** [comment]
Ok, thanks for letting me know. I was going to update to 1.19.2 anyway in the next few months. Glad to know there's already a fix for it.

**Comment by comp500** [comment]
Closing: insufficient information
