### ISSUE TITLE
minecraft stuck in borderless even without the mod

### ISSUE THREAD

**Issue by Pietr06** [comp500/BorderlessMining#61]
idk if im missing something, but iv loaded mc with the mod once, and now all the instances of prism launcher use borderless mode, even without having ever installed the mod on that instance, if i use the vanilla launcher instead it uses normal window mode
the first time i used the mod was on a 1.18.2 instance

**Comment by comp500** [comment]
Do you use a mod that preserves the window position? What operating system do you use?

**Comment by Pietr06** [comment]
mmm dont think any of the mods i have do that thing, and it also happens with totally vanilla instances, i use windows 11 22h2

**Comment by comp500** [comment]
I don't know then, I don't think this is something caused by Borderless Mining. If you're using a laptop with a dedicated GPU, the difference might be that Prism isn't using your dedicated GPU - you can configure which GPU is used by the `javaw.exe` Prism uses in the Windows graphics settings.

**Comment by Pietr06** [comment]
> I don't know then, I don't think this is something caused by Borderless Mining. If you're using a laptop with a dedicated GPU, the difference might be that Prism isn't using your dedicated GPU - you can configure which GPU is used by the `javaw.exe` Prism uses in the Windows graphics settings.

i have a laptop with only the integrated gpu, so idrk
