### ISSUE TITLE
[Fabric] The mod doesn't do anything

### ISSUE THREAD

**Issue by skunkmommy** [comp500/BorderlessMining#70]
I still can't see the game when I tab out, it's as if the mod legit isn't doing anything.
Fabric 1.19.4, 1.1.7

**Comment by comp500** [comment]
By "see the game when you tab out" do you mean you have multiple monitors and the game minimises when you switch away? or are you just unable to have other windows (or the start menu/etc) on top?

Additionally, what operating system and graphics drivers/GPUs are you using?

**Comment by skunkmommy** [comment]
I have multiple monitors and the game minimises when I switch away.
I'm on Windows 10 22H2 build 19045.2846 
I have a GTX 1650, I don't know how to check the driver version.

**Comment by rebub** [comment]
Hey, i suffer from the same problem.. even while using (shift p) with sodium i can't put it on borderless.. its either on fullscreen or not.

edit: got it.. but somehow takes as long as fullscreen to alt+tab

**Comment by skunkmommy** [comment]
I don't think it mentions anywhere that you have to do shift+p for it to work. This should at least be documented to some degree.

**Comment by rebub** [comment]
Because of sodium i wasn't being able to turn it on for some reason.. so shift+p helped but like i said its in window borderless mode but: "somehow takes as long as fullscreen to alt+tab"

**Comment by comp500** [comment]
> I don't think it mentions anywhere that you have to do shift+p for it to work. This should at least be documented to some degree.

Sodium is the mod that replaces the video settings screen entirely and adds the keybind, so this is not the fault of Borderless Mining; without it the mod is configurable directly from the video settings. Even with Sodium, Borderless Mining has a settings screen accessible from Mod Menu. Either way, Borderless Mining is enabled by default - this would only ever occur if the modpack creator or you already disabled it.

**Comment by comp500** [comment]
> Because of sodium i wasn't being able to turn it on for some reason.. so shift+p helped but like i said its in window borderless mode but: "somehow takes as long as fullscreen to alt+tab"

This is a known issue, see https://github.com/comp500/BorderlessMining/issues/19
