### ISSUE TITLE
Fabric 1.20

### ISSUE THREAD

**Issue by kada49** [comp500/BorderlessMining#73]
Could you add support for  Fabric 1.20? I already forked the project (https://github.com/kada49/BorderlessMining) and adapted the code to (probably) work in the newer version. I also did not open a merge request, since there is no 1.20 branch to merge to.

Thanks! :)

**Comment by FractalGeodes** [comment]
The mod dev will get around to it when they get time, but for now I've found extracting the jar file and changing the minecraft version match to `1.20` worked, at least on the title screen. There may be bugs though, so if you follow this method don't bother reporting them here.

**Comment by vico93** [comment]
> The mod dev will get around to it when they get time, but for now I've found extracting the jar file and changing the minecraft version match to `1.20` worked, at least on the title screen. There may be bugs though, so if you follow this method don't bother reporting them here.

You can do a dependency override instead of changing the version manually on the meta file inside the jar. Just create a file called `fabric_loader_dependencies.json` in your instance's config folder and put this in it:

```json
{
  "version": 1,
  "overrides": {
    "borderlessmining": {
      "-depends": {
        "minecraft": "IGNORED"
      }
    }
  }
}
```

**Comment by Polda18** [comment]
> > The mod dev will get around to it when they get time, but for now I've found extracting the jar file and changing the minecraft version match to `1.20` worked, at least on the title screen. There may be bugs though, so if you follow this method don't bother reporting them here.
> 
> You can do a dependency override instead of changing the version manually on the meta file inside the jar. Just create a file called `fabric_loader_dependencies.json` in your instance's config folder and put this in it:
> 
> ```json
> {
>   "version": 1,
>   "overrides": {
>     "borderlessmining": {
>       "-depends": {
>         "minecraft": "IGNORED"
>       }
>     }
>   }
> }
> ```

Thanks, that worked. And yes, it does work in game as well, not just in main menu. I would prefer a regular new version for 1.20, but that worked.

**Comment by nolanbarry** [comment]
I wasn't smart enough to figure out how to use quilt dependency overrides feature so I modified the mod file directly:
1. Rename `borderless-mining-1.17+1.19.4.jar` to `borderless-mining-1.17+1.19.4.zip`
2. Extract the zip file into a folder and open `fabric.mod.json`
3. Change the `"depends"` property to depend on 1.20:
```json
  ...
  "depends": {
    "fabricloader": "\u003e\u003d0.7.2",
    "fabric-resource-loader-v0": "*",
    "minecraft": "1.20"
  },
  ...
```
4. Zip all your files back up, rename the zip file back into a jar file. Make sure the contents are directly in the zip file, and that you didn't zip a folder into another folder.

**Comment by Felix14-v2** [comment]
@nolanbarry , you can just edit file inside the jar using WinRAR, without extracting

**Comment by vico93** [comment]
ah, seems that even with the fabric_dependencies trick, the mod still crashes when one tries to go to the config on mod menu (Crash Report [HERE](https://gist.github.com/vico93/91319563276180aebfcbfc4f248102a7)).

@kada49 could you do a build of your fork for me to test?

**Comment by RealKomander** [comment]
I managed to get it working, after changing `fabric_loader_dependencies.json` and `fabric.mod.json` you also need to enable borderless fullscreen in `config\borderlessmining.json` via notepad
