### ISSUE TITLE
Not real borderless

### ISSUE THREAD

**Issue by Cooliosity** [comp500/BorderlessMining#75]
When I set other games to borderless, i can still watch youtube videos in picture in picture mode. However when i use this mod, the minecraft window is the topmost window, forcing me to use windowed mode when i want to watch videos. Is this a limitation or an oversight?

**Comment by Cooliosity** [comment]
I have now removed the mod and instead tried using the borderless gaming program. Minecraft still behaves in the same way so I guess it's actually an issue related to Minecraft and not to this mod

**Comment by canthisbe** [comment]
The experimental GLFW patch fixes this: #19
