### ISSUE TITLE
Just not working

### ISSUE THREAD

**Issue by jsaperr** [comp500/BorderlessMining#79]
I have the slider set to borderless, and using normal video settings instead of sodium, when selecting fullscreen it just is normal fullscreen, tested with trying to display livesplit over it.

**Comment by comp500** [comment]
This is a known issue and I'm working on a fix, see https://github.com/comp500/BorderlessMining/issues/19 - many graphics drivers will force exclusive fullscreen for all OpenGL applications on Windows.

**Comment by jsaperr** [comment]
awesome, glad its known, thanks!
