### ISSUE TITLE
It just doesnt work correctly

### ISSUE THREAD

**Issue by StevieTheDragon** [comp500/BorderlessMining#81]
For version 1.20.1 when doing alt tab to go back to chrome or any other window there's a big black screen delay just as if you were in fullscreen. Simply doesnt fix the fullscreen issue at all.

**Comment by comp500** [comment]
This is a known issue and I'm working on a fix, see https://github.com/comp500/BorderlessMining/issues/19 - many graphics drivers will force exclusive fullscreen for all OpenGL applications on Windows.
