### ISSUE TITLE
Borderless window doesn't work properly

### ISSUE THREAD

**Issue by KAkos1220** [comp500/BorderlessMining#85]
If I launch Minecraft and trying to press the WIN key It's doesn't work (but the start menu is getting opened because I can click on the icons, I just don't see them)
Also, if I'm trying to click between my monitors, the Minecraft window is flickering.
My temporary solution is to put it in fullscreen and then out 8 times and it's got solved.
BTW if I put the whole Minecraft window to my 2nd monitor It's working fine after launch.
Here's a video about the problem:
https://1drv.ms/v/s!Ark72AiNiKhtg6cB2ZL3xEipK3r_JA?e=8MBlbJ

PS: I have a Ryzen 5 5600x, Rx 6600xt (latest drivers)

**Comment by KAkos1220** [comment]
⚠️UPDTATE⚠️:
I did a ,,little" research...
If you use an AMD gpu and you have any problems with the mod, the following method will solve the problems: (hopefully)
1.Open AMD adrenalin software
2.Go to the Gaming tab
3. Select Graphics on the top
4. Scroll down to Advanced
5. And enable  ,,OpenGL triple buffering"
![image](https://github.com/comp500/BorderlessMining/assets/143555255/e6fb7e12-c0dc-4ec5-af75-46db76d0e702)

I'm glad if I could help😁
(+ you get more fps)

**Comment by comp500** [comment]
This is a known issue and I'm working on a fix, see https://github.com/comp500/BorderlessMining/issues/19 - many graphics drivers will force exclusive fullscreen for all OpenGL applications on Windows.
