### ISSUE TITLE
Crash trying to access mod's settings in 1.20.4

### ISSUE THREAD

**Issue by vico93** [comp500/BorderlessMining#92]
Got [this crash](https://gist.github.com/vico93/ed5d0b3da8d1a498b2febb089f41c8a0) when trying to access the mod settings in ModMenu.

Minecraft: 1.20.4
Fabric (loader): 0.15.3
Fabric (API): 0.93.1

**Comment by comp500** [comment]
Duplicate of https://github.com/comp500/BorderlessMining/issues/90
